name: "bluebell"
mode: "dev"
port: 23456
version: "v0.0.1"
start_time: "2022-12-25"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "./log/bluebell.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: "127.0.0.1"
  port: 
  user: ""
  password: ""
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "localhost"
  port: 
  password: ""
  db: 0
  pool_size: 100
